version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: docker/aws/scripts/deploy.sh
      timeout: 300
      runas: root
branch_config:
    main:
        deploymentGroupName: demo
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::590183784162:role/codedeployrole
