name: Deployment on AWS
on:
  push:
    branches:
      - stage
      - quality
      - production
    
jobs:
  get-environment:
    name: Get environment
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github code
      id: checkout-id
      uses: actions/checkout@v4
    - id: setenv
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
          echo "my_env=stage" >> $GITHUB_OUTPUT          
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "my_env=main" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
          echo "my_env=production" >> $GITHUB_OUTPUT
        fi


  # AI Chat
  # =======================================================
  ai-chat:
    if: contains(github.event.head_commit.message, 'deploy chat')
    name: Deploying AI Chat
    runs-on: ubuntu-latest
    needs: get-environment
    environment: 
      name: ${{ needs.get-environment.outputs.my_env }}
    permissions:
      contents: write
    steps:
      - name: Checkout github code
        id: checkout-id
        uses: actions/checkout@v4
      - name: Test Variables
        run: |
          echo "${{ vars.ENVIRONMENT }}"
          echo "${{ vars.AWS_DEFAULT_REGION }}"
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Get branch name
        id: branch
        shell: bash
        run: echo "name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Echo branch name
        run: |
          echo ${{ steps.branch.outputs.name }}
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pushing image
        id: build-image-chat
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ENVIRONMENT }}_ai_chat_luminous
          IMAGE_TAG: ${{ vars.ENVIRONMENT }}
        run: |
          docker build -f docker/aws/chat/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image-chat=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

